schema-version: v2
kind: plugin
metadata:
  name: nodejs-backend-base
  display-name: nodejs-backend-base
  description: Base content for a backend service
  version: 0.0.1
  picture: plugin.png
spec:
  type: app
  compatibility:
    - typescript
  docs:
    pt-br: docs/pt-br/docs.md
    en-us: docs/en-us/docs.md
  single-use: true
  technologies: # Ref: https://docs.stackspot.com/create-use/create-content/yaml-files/plugin-yaml/#technologies-1
    - TypeScript
  stk-projects-only: false
  inputs:
    - label: Application Description
      name: app_description
      type: text
      required: true
      help: "Inform your app name (e.g.: example-api)"
    - label: Choose an Architecture Type
      name: arch
      type: select
      items:
        - Hexagonal
        - MVC
        - Clean Architecture
        - None
      default: None
      required: true
      global: true
      help: "Inform the architecture you desire to use in the application"
    - label: Choose the Package Manager
      name: package_manager
      type: select
      items:
        - npm
        - yarn
        - pnpm
      default: npm
      required: true
      global: true
      help: "Inform which NodeJS package manager to use"
  hooks:
    - type: run-script
      trigger: before-render
      script: scripts/before-render.py
    - type: render-templates
      trigger: after-render
      path: snippets/hexagonal
      condition:
        variable: arch
        operator: "=="
        value: Hexagonal
    - type: render-templates
      trigger: after-render
      path: snippets/clean
      condition:
        variable: arch
        operator: "=="
        value: Clean Architecture
    - type: render-templates
      trigger: after-render
      path: snippets/mvc
      condition:
        variable: arch
        operator: "=="
        value: MVC
    - type: run
      trigger: after-render
      commands:
        - echo {{package_manager}} --version
        - "{{package_manager}} install"
